-- MySQL Script generated by MySQL Workbench
-- 01/20/20 20:08:42
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema SIM_Registaration
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema SIM_Registaration
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SIM_Registaration` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `SIM_Registaration` ;

-- -----------------------------------------------------
-- Table `SIM_Registaration`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SIM_Registaration`.`User` (
  `UserID` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `UserName` VARCHAR(45) NULL COMMENT '',
  `Password` VARCHAR(45) NULL COMMENT '',
  `Forgot Password` VARCHAR(45) NULL COMMENT '',
  `FirstName` VARCHAR(45) NULL COMMENT '',
  `LastName` VARCHAR(45) NULL COMMENT '',
  `Address` VARCHAR(200) NULL COMMENT '',
  `NICnumber` VARCHAR(15) NULL COMMENT '',
  `Contact Number` VARCHAR(15) NULL COMMENT '',
  `Usercol` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`UserID`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SIM_Registaration`.`SIM`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SIM_Registaration`.`SIM` (
  `SIM Id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `SIM Number` INT NULL COMMENT '',
  `NIC Image` VARCHAR(45) NULL COMMENT '',
  `First Name` MEDIUMBLOB NULL COMMENT '',
  `Last Name` VARCHAR(45) NULL COMMENT '',
  `NIC Number` INT NULL COMMENT '',
  `Address` VARCHAR(45) NULL COMMENT '',
  `Gender` VARCHAR(45) NULL COMMENT '',
  `SIM Category` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`SIM Id`)  COMMENT '')
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
